name: Deploy Node.js app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# 👇 Necesario para azure/login con federación OIDC
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build (if present)
        run: npm run build --if-present

      - name: Archive app
        run: |
          zip -r app.zip . -x ".git/*" ".github/*" "node_modules/*" "**/.env*" "**/*.md"

      - name: Azure Login (Managed Identity)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E78D8513ADEE422C95AD4B3F474E7C9C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E2B4BFE27D54503818D78B916F34573 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BD9142D8C3364897891993447532779E }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: api-paises-node-minvu
          slot-name: Production
          package: app.zip
